
{
  "models": [
    {
      "title": "GPT-4.1 Azure",
      "provider": "openai",
      "apiBase": "https://regis-svfilho-3835-resource.services.ai.azure.com/openai/v1",
      "apiKey": "",
      "model": "gpt-4.1"
    }
  ]
}
